//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Сourse_management.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses_Status
    {
        public Courses_Status()
        {
            this.Student_Courses = new HashSet<Student_Courses>();
            this.Student_Lessons = new HashSet<Student_Lessons>();
        }
    
        public int Status_Id { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Student_Courses> Student_Courses { get; set; }
        public virtual ICollection<Student_Lessons> Student_Lessons { get; set; }
    }
}
