//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Сourse_management.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {
        public Courses()
        {
            this.Lessons = new HashSet<Lessons>();
            this.Student_Courses = new HashSet<Student_Courses>();
        }
    
        public int Courses_Id { get; set; }
        public string Courses_Name { get; set; }
        public string Courses_Descriptions { get; set; }
        public Nullable<int> Courses_Part { get; set; }
        public string Courses_Image { get; set; }
        public int Language_Id { get; set; }
    
        public virtual language language { get; set; }
        public virtual ICollection<Lessons> Lessons { get; set; }
        public virtual ICollection<Student_Courses> Student_Courses { get; set; }
    }
}
