//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Сourse_management.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public Cours()
        {
            this.Lessons = new HashSet<Lesson>();
            this.Student_Courses = new HashSet<Student_Courses>();
        }
    
        public int Courses_Id { get; set; }
        public string Courses_Name { get; set; }
        public string Courses_Descriptions { get; set; }
        public Nullable<int> Courses_Part { get; set; }
        public Nullable<int> Creator_Id { get; set; }
        public double Curses_Price { get; set; }
        public string Courses_Image { get; set; }
        public string Courses_programming_language { get; set; }
    
        public virtual Creator Creator { get; set; }
        public virtual ICollection<Lesson> Lessons { get; set; }
        public virtual ICollection<Student_Courses> Student_Courses { get; set; }
    }
}
