//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Сourse_management.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Creator
    {
        public int Creator_Id { get; set; }
        public string Creator_Education { get; set; }
        public string Creator_Education2 { get; set; }
        public string Creator_Experience { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
