//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Сourse_management.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class language
    {
        public language()
        {
            this.Courses = new HashSet<Courses>();
        }
    
        public int Language_Id { get; set; }
        public string Language1 { get; set; }
    
        public virtual ICollection<Courses> Courses { get; set; }
    }
}
