//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Сourse_management.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public Lesson()
        {
            this.Student_Lessons = new HashSet<Student_Lessons>();
            this.Tasks = new HashSet<Task>();
        }
    
        public int Lessons_Id { get; set; }
        public int Courses_Id { get; set; }
        public int Lessons_Part { get; set; }
        public string Lessons_Name { get; set; }
        public string Lessons_Content { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual ICollection<Student_Lessons> Student_Lessons { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
