//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Сourse_management.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Lessons
    {
        public int Student_Lessons_Id { get; set; }
        public int Student_Courses_Id { get; set; }
        public int Lessons_Id { get; set; }
        public int Status_Id { get; set; }
    
        public virtual Courses_Status Courses_Status { get; set; }
        public virtual Lesson Lesson { get; set; }
        public virtual Student_Courses Student_Courses { get; set; }
    }
}
