//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Сourse_management.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Student_Courses = new HashSet<Student_Courses>();
        }
    
        public int Student_Id { get; set; }
        public string Student_SurName { get; set; }
        public string Student_Name { get; set; }
        public string Student_LastName { get; set; }
        public string Student_Age { get; set; }
        public string Student_Gender { get; set; }
        public string Student_Number { get; set; }
    
        public virtual Creator Creator { get; set; }
        public virtual ICollection<Student_Courses> Student_Courses { get; set; }
        public virtual User User { get; set; }
    }
}
