//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Сourse_management.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Tasks_Id { get; set; }
        public int Lessons_Id { get; set; }
        public string Tasks_Name { get; set; }
        public string Tasks_Text { get; set; }
        public string Tasks_Answer { get; set; }
        public int Tasks_Number { get; set; }
    
        public virtual Lesson Lesson { get; set; }
    }
}
