//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Сourse_management.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Users_Id { get; set; }
        public int Role_Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Student Student { get; set; }
    }
}
